import Task from "../models/task.model.js";

export const getTasks = async (req, res) => {
  try {
    const tasks = await Task.find({
      user: req.user.id,
    }).populate("user");
    res.json(tasks);
  } catch (error) {
    return res.status(404).json({ message: "Task no found" });
  }
};
//Populate en mongoose se utiliza para remplazar automaticamente el campo de referencia en un documento
//con el documento real al que hace referencia en otra coleccion

export const createTask = async (req, res) => {
  //Este es para crear una tarea, el newtaks es el esquema de la tarea
  try {
    const { title, description, date } = req.body;
    const newTask = new Task({
      title,
      description,
      date,
      user: req.user.id,
    });
    const savedTask = await newTask.save();
    res.json(savedTask);
  } catch (error) {
    return res.status(404).json({ message: "Task no found" });
  }
};
//

export const getTask = async (req, res) => {
  try {
    const task = await Task.findById(req.params.id).populate("user");
    if (!task) return res.status(404).json({ message: "Task no found " });
    res.json(task);
  } catch (error) {
    return res.status(404).json({ message: "Task no found" });
  }
};
export const deleteTask = async (req, res) => {
  try {
    const task = await Task.findByIdAndDelete(req.params.id);
    if (!task) return res.status(404).json({ message: "Task not found" });
    return res.sendStatus(204);
  } catch (error) {
    return res.status(404).json({ message: "Task no found" });
  }
};
export const updateTask = async (req, res) => {
  try {
    const task = await Task.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
    });
    if (!task) return res.status(404).json({ message: "Task not found" });
    res.json(task);
  } catch (error) {
    return res.status(404).json({ message: "Task no found" });
  }
};

//Ponemos a todas la peticiones dentro de un try catch por que si llega  a fallar nos lance el error y no nos
//tumbe el servidor
